/**
 * Embedded Pre-cached Knowledge Base & Reference Data
 * Contains Rijal (narrator biographical entries), Hadith Corpus, and 5 Rules Definitions.
 */

const NARRATORS_DATA = {
  "prophet_muhammad": {
    "id": "prophet_muhammad",
    "name_ar": "رسول الله محمد ﷺ",
    "name_en": "Prophet Muhammad ﷺ",
    "name_ur": "رسول اللہ محمد مصطفیٰ ﷺ",
    "generation": "Prophet",
    "generation_ar": "النبي المصطفى ﷺ",
    "generation_ur": "نبی آخر الزماں ﷺ",
    "death_hijri": 11,
    "city": "Madinah",
    "reliability_tier": "prophetic_source",
    "integrity_score": 100,
    "memory_score": 100,
    "is_mudallis": false,
    "notes_en": "The final Messenger of Allah, source of prophetic revelation and Sunnah.",
    "notes_ar": "خاتم الأنبياء والمرسلين ومصدر الوحي والسنة المطهرة.",
    "notes_ur": "اللہ کے آخری رسول اور تمام احادیث و سنت کے منبع۔"
  },
  "umar_ibn_al_khattab": {
    "id": "umar_ibn_al_khattab",
    "name_ar": "عمر بن الخطاب رضي الله عنه",
    "name_en": "Umar ibn al-Khattab (RA)",
    "name_ur": "حضرت عمر بن الخطاب رضی اللہ عنہ",
    "generation": "Sahabi",
    "generation_ar": "صحابي جليل - أمير المؤمنين",
    "generation_ur": "جلیل القدر صحابی - امیر المومنین",
    "death_hijri": 23,
    "city": "Madinah",
    "reliability_tier": "sahabi_adl",
    "integrity_score": 100,
    "memory_score": 100,
    "is_mudallis": false,
    "notes_en": "Second Rightly Guided Caliph. Companions are upright by consensus.",
    "notes_ar": "الخليفة الراشد الثاني، الصحابة كلهم عدول بتعديل الله تعالى.",
    "notes_ur": "خلیفہ راشد ثانی۔ اہل السنت کے اجماع کے مطابق تمام صحابہ عادل ہیں۔"
  },
  "abu_hurayrah": {
    "id": "abu_hurayrah",
    "name_ar": "أبو هريرة رضي الله عنه",
    "name_en": "Abu Hurayrah (RA)",
    "name_ur": "حضرت ابوہریرہ رضی اللہ عنہ",
    "generation": "Sahabi",
    "generation_ar": "صحابي جليل - أحفظ الصحابة",
    "generation_ur": "سب سے زیادہ احادیث یاد رکھنے والے صحابی",
    "death_hijri": 57,
    "city": "Madinah",
    "reliability_tier": "sahabi_adl",
    "integrity_score": 100,
    "memory_score": 100,
    "is_mudallis": false,
    "notes_en": "Most prolific companion narrator; prayed for retentive memory by the Prophet ﷺ.",
    "notes_ar": "أحفظ الصحابة للحديث النبوي الشريف.",
    "notes_ur": "سب سے زیادہ روایات یاد رکھنے والے صحابی رسول۔"
  },
  "abdullah_ibn_umar": {
    "id": "abdullah_ibn_umar",
    "name_ar": "عبد الله بن عمر رضي الله عنهما",
    "name_en": "Abdullah ibn Umar (RA)",
    "name_ur": "حضرت عبداللہ بن عمر رضی اللہ عنہما",
    "generation": "Sahabi",
    "generation_ar": "صحابي جليل - فقيه الأمة",
    "generation_ur": "جلیل القدر صحابی و فقیہ",
    "death_hijri": 73,
    "city": "Madinah",
    "reliability_tier": "sahabi_adl",
    "integrity_score": 100,
    "memory_score": 100,
    "is_mudallis": false,
    "notes_en": "Renowned for exacting devotion to the prophetic Sunnah.",
    "notes_ar": "من المكثرين في الرواية وشديد التمسك بالآثار.",
    "notes_ur": "سنت رسول ﷺ کی اتباع میں بے مثال صحابی۔"
  },
  "anas_ibn_malik": {
    "id": "anas_ibn_malik",
    "name_ar": "أنس بن مالك رضي الله عنه",
    "name_en": "Anas ibn Malik (RA)",
    "name_ur": "حضرت انس بن مالک رضی اللہ عنہ",
    "generation": "Sahabi",
    "generation_ar": "خادم رسول الله ﷺ",
    "generation_ur": "خادم خاص رسول اللہ ﷺ",
    "death_hijri": 93,
    "city": "Basra",
    "reliability_tier": "sahabi_adl",
    "integrity_score": 100,
    "memory_score": 100,
    "is_mudallis": false,
    "notes_en": "Served the Prophet ﷺ for a decade in Madinah.",
    "notes_ar": "خادم النبي ﷺ لعشر سنين، من مكثري الرواية.",
    "notes_ur": "رسول اللہ ﷺ کی دس سال تک خدمت کرنے والے صحابی۔"
  },
  "nafi_mawla_ibn_umar": {
    "id": "nafi_mawla_ibn_umar",
    "name_ar": "نافع مولى ابن عمر",
    "name_en": "Nafi' Mawla Ibn Umar",
    "name_ur": "نافع مولیٰ ابن عمر",
    "generation": "Wusta al-Tabi'in",
    "generation_ar": "الوسطى من التابعين",
    "generation_ur": "وسطیٰ تابعین",
    "death_hijri": 117,
    "city": "Madinah",
    "reliability_tier": "thiqah_hafiz",
    "integrity_score": 100,
    "memory_score": 100,
    "is_mudallis": false,
    "notes_en": "Core transmitter in the Golden Chain (Silsilat al-Dhahab).",
    "notes_ar": "ركن سلسلة الذهب وإمام التثبت.",
    "notes_ur": "سلسلۃ الذہب (سنہری زنجیر) کی مرکزی کڑی۔"
  },
  "al_zuhri": {
    "id": "al_zuhri",
    "name_ar": "ابن شهاب الزهري",
    "name_en": "Ibn Shihab al-Zuhri",
    "name_ur": "ابن شہاب زہری",
    "generation": "Sughra al-Tabi'in",
    "generation_ar": "صغار التابعين",
    "generation_ur": "صغار تابعین",
    "death_hijri": 124,
    "city": "Madinah",
    "reliability_tier": "thiqah_hafiz",
    "integrity_score": 100,
    "memory_score": 98,
    "is_mudallis": true,
    "mudallis_tier": 2,
    "notes_en": "Pioneering codifier of the Hadith corpus. Unrivaled memorizer.",
    "notes_ar": "أول من دوّن الحديث النبوي، إمام الحجاز والشام.",
    "notes_ur": "حدیث نبوی کے پہلے جامع و مدون۔"
  },
  "alqamah_ibn_waqqas": {
    "id": "alqamah_ibn_waqqas",
    "name_ar": "علقمة بن وقاص الليثي",
    "name_en": "Alqamah ibn Waqqas al-Laythi",
    "name_ur": "علقمہ بن وقاص اللیثی",
    "generation": "Kibar al-Tabi'in",
    "generation_ar": "كبار التابعين",
    "generation_ur": "کبار تابعین",
    "death_hijri": 85,
    "city": "Madinah",
    "reliability_tier": "thiqah_hafiz",
    "integrity_score": 100,
    "memory_score": 98,
    "is_mudallis": false,
    "notes_en": "Sole transmitter of Hadith of Intentions from Umar (RA). Thiqah Thabat.",
    "notes_ar": "راوي حديث النيات عن عمر، ثقة ثبت متفق عليه.",
    "notes_ur": "حضرت عمر سے حدیث نیت کے راوی، ثقہ ثبت۔"
  },
  "muhammad_ibn_ibrahim_al_taymi": {
    "id": "muhammad_ibn_ibrahim_al_taymi",
    "name_ar": "محمد بن إبراهيم التيمي",
    "name_en": "Muhammad ibn Ibrahim al-Taymi",
    "name_ur": "محمد بن ابراہیم التیمی",
    "generation": "Wusta al-Tabi'in",
    "generation_ar": "الوسطى من التابعين",
    "generation_ur": "وسطیٰ تابعین",
    "death_hijri": 120,
    "city": "Madinah",
    "reliability_tier": "thiqah_hafiz",
    "integrity_score": 100,
    "memory_score": 96,
    "is_mudallis": false,
    "notes_en": "Transmitter from Alqamah. Highly praised by Hadith critics.",
    "notes_ar": "راوي حديث النيات عن علقمة، ثقة حجة.",
    "notes_ur": "علقمہ سے حدیث نیت کے راوی، ثقہ و معتبر۔"
  },
  "yahya_ibn_said_al_ansari": {
    "id": "yahya_ibn_said_al_ansari",
    "name_ar": "يحيى بن سعيد الأنصاري",
    "name_en": "Yahya ibn Sa'id al-Ansari",
    "name_ur": "یحییٰ بن سعید الانصاری",
    "generation": "Sughra al-Tabi'in",
    "generation_ar": "صغار التابعين",
    "generation_ur": "صغار تابعین",
    "death_hijri": 143,
    "city": "Madinah",
    "reliability_tier": "thiqah_hafiz",
    "integrity_score": 100,
    "memory_score": 98,
    "is_mudallis": false,
    "notes_en": "Judge of Madinah. Over 200 trustworthy scholars narrated from him.",
    "notes_ar": "قاضي المدينة وإمام ثبت، عنه انتشر حديث النيات.",
    "notes_ur": "قاضی مدینہ، جن سے حدیث نیت بیسیوں ائمہ نے روایت کی۔"
  },
  "malik_ibn_anas": {
    "id": "malik_ibn_anas",
    "name_ar": "الإمام مالك بن أنس",
    "name_en": "Imam Malik ibn Anas",
    "name_ur": "امام مالک بن انس",
    "generation": "Atba' al-Tabi'in",
    "generation_ar": "إمام دار الهجرة",
    "generation_ur": "امام دار الہجرہ",
    "death_hijri": 179,
    "city": "Madinah",
    "reliability_tier": "thiqah_hafiz",
    "integrity_score": 100,
    "memory_score": 100,
    "is_mudallis": false,
    "notes_en": "Imam Dar al-Hijrah, compiler of Al-Muwatta. Pristine narrator screening.",
    "notes_ar": "إمام دار الهجرة ونجم العلماء، شديد التحري.",
    "notes_ur": "امام دار الہجرہ اور صاحبِ موطا، روات کی سخت جانچ کرنے والے۔"
  },
  "sufyan_ibn_uyaynah": {
    "id": "sufyan_ibn_uyaynah",
    "name_ar": "سفيان بن عيينة",
    "name_en": "Sufyan ibn Uyaynah",
    "name_ur": "سفیان بن عیینہ",
    "generation": "Atba' al-Tabi'in",
    "generation_ar": "إمام الحرم المكي",
    "generation_ur": "امام اہل مکہ",
    "death_hijri": 198,
    "city": "Makkah",
    "reliability_tier": "thiqah_hafiz",
    "integrity_score": 100,
    "memory_score": 98,
    "is_mudallis": true,
    "mudallis_tier": 1,
    "notes_en": "Pillar of Hadith in Makkah. Teacher of Al-Shafi'i and Ahmad.",
    "notes_ar": "إمام مكة وحافظ ثقة ثبت.",
    "notes_ur": "مکہ مکرمہ کے عظیم امام اور حافظ حدیث۔"
  },
  "al_humaydi": {
    "id": "al_humaydi",
    "name_ar": "عبد الله بن الزبير الحميدي",
    "name_en": "Al-Humaydi (Abdullah ibn al-Zubayr)",
    "name_ur": "عبداللہ بن زبیر الحمیدی",
    "generation": "Atba' Atba' al-Tabi'in",
    "generation_ar": "شيخ البخاري ومصنف المسند",
    "generation_ur": "شیخ البخاری",
    "death_hijri": 219,
    "city": "Makkah",
    "reliability_tier": "thiqah_hafiz",
    "integrity_score": 100,
    "memory_score": 98,
    "is_mudallis": false,
    "notes_en": "Prominent teacher of Imam Al-Bukhari; compiler of Musnad al-Humaydi.",
    "notes_ar": "شيخ البخاري الذي افتتح به صحيحه.",
    "notes_ur": "امام بخاری کے جلیل القدر استاد جن سے پہلی حدیث مروی ہے۔"
  },
  "al_bukhari": {
    "id": "al_bukhari",
    "name_ar": "الإمام محمد بن إسماعيل البخاري",
    "name_en": "Imam Muhammad ibn Isma'il al-Bukhari",
    "name_ur": "امام محمد بن اسماعیل بخاری",
    "generation": "A'immat al-Hadith",
    "generation_ar": "أمير المؤمنين في الحديث",
    "generation_ur": "امیر المومنین فی الحدیث",
    "death_hijri": 256,
    "city": "Bukhara",
    "reliability_tier": "thiqah_hafiz",
    "integrity_score": 100,
    "memory_score": 100,
    "is_mudallis": false,
    "notes_en": "Amir al-Mu'minin fi al-Hadith. Compiler of Sahih al-Bukhari.",
    "notes_ar": "أمير المؤمنين في الحديث وصاحب أصح كتاب بعد كتاب الله.",
    "notes_ur": "حدیث کے امام اعظم جن کی کتاب قرآن کے بعد سب سے معتبر ہے۔"
  },
  "al_tirmidhi": {
    "id": "al_tirmidhi",
    "name_ar": "الإمام أبو عيسى الترمذي",
    "name_en": "Imam Abu Isa al-Tirmidhi",
    "name_ur": "امام ابو عیسیٰ ترمذی",
    "generation": "A'immat al-Hadith",
    "generation_ar": "صاحب السنن",
    "generation_ur": "جامع ترمذی کے مصنف",
    "death_hijri": 279,
    "city": "Termez",
    "reliability_tier": "thiqah_hafiz",
    "integrity_score": 100,
    "memory_score": 98,
    "is_mudallis": false,
    "notes_en": "Compiler of Jami' at-Tirmidhi; established definitions of Hasan Hadith.",
    "notes_ar": "صاحب الجامع ومحرر مصطلح الحديث والعلل.",
    "notes_ur": "جامع ترمذی کے مؤلف جنہوں نے حدیث حسن کو منضبط کیا۔"
  },
  "abu_atikah": {
    "id": "abu_atikah",
    "name_ar": "أبو عاتكة طريف بن سلمان",
    "name_en": "Abu Atikah Tarif ibn Salman",
    "name_ur": "ابو عاتکہ طریف بن سلمان",
    "generation": "Atba' al-Tabi'in",
    "generation_ar": "متروك الحديث",
    "generation_ur": "متروک الحدیث",
    "death_hijri": 160,
    "city": "Basra",
    "reliability_tier": "matruk",
    "integrity_score": 15,
    "memory_score": 10,
    "is_mudallis": false,
    "notes_en": "Transmitter of the rejected 'Seek knowledge in China' report. Matruk al-Hadith.",
    "notes_ar": "راوي حديث 'اطلبوا العلم ولو بالصين'، متروك منكر الحديث.",
    "notes_ur": "چین والی روایت کا راوی، تمام ائمہ کے نزدیک متروک ہے۔"
  },
  "habib_ibn_abi_habib": {
    "id": "habib_ibn_abi_habib",
    "name_ar": "حبيب بن أبي حبيب المروزي",
    "name_en": "Habib ibn Abi Habib al-Marwazi",
    "name_ur": "حبیب بن ابی حبیب المروزی",
    "generation": "Atba' al-Tabi'in",
    "generation_ar": "كذاب وضاع",
    "generation_ur": "کذاب اور حدیث گھڑنے والا",
    "death_hijri": 170,
    "city": "Marw",
    "reliability_tier": "kadhdhab",
    "integrity_score": 0,
    "memory_score": 5,
    "is_mudallis": false,
    "notes_en": "Known fabricator. Fabricated chains falsely attributed to Imam Malik.",
    "notes_ar": "كذاب وضاع يضع الأحاديث على مالك والثقات.",
    "notes_ur": "جھوٹا اور حدیث گھڑنے والا راوی۔"
  }
};

const CORPUS_DATA = [
  {
    "id": "hadith_niyyah",
    "title_en": "Hadith of Intentions (Innama al-A'malu bin-Niyyat)",
    "title_ar": "حديث الأعمال بالنيات",
    "title_ur": "حدیث نیت (اعمال کا دارومدار نیتوں پر ہے)",
    "book": "Sahih al-Bukhari #1 / Muslim #1907",
    "matn_ar": "إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى، فَمَنْ كَانَتْ هِجْرَتُهُ إِلَى دُنْيَا يُصِيبُهَا أَوْ إِلَى امْرَأَةٍ يَنْكِحُهَا، فَهِجْرَتُهُ إِلَى مَا هَاجَرَ إِلَيْهِ.",
    "matn_en": "Actions are but by intentions, and every person will have only what he intended...",
    "matn_ur": "اعمال کا دارومدار نیتوں پر ہے اور ہر انسان کے لیے وہی ہے جس کی اس نے نیت کی...",
    "narrator_ids": [
      "al_bukhari",
      "al_humaydi",
      "sufyan_ibn_uyaynah",
      "yahya_ibn_said_al_ansari",
      "muhammad_ibn_ibrahim_al_taymi",
      "alqamah_ibn_waqqas",
      "umar_ibn_al_khattab",
      "prophet_muhammad"
    ],
    "transmission_formulas": ["haddathana", "haddathana", "haddathana", "akhbarana", "sami'tu", "sami'tu", "sami'tu"],
    "known_verdict": "SAHIH",
    "known_sub_verdict": "Sahih li-dhatihi (Muttafaq 'Alayh)",
    "badge_class": "sahih"
  },
  {
    "id": "hadith_golden_chain",
    "title_en": "The Golden Chain (Silsilat al-Dhahab) - Brotherly Love",
    "title_ar": "سلسلة الذهب: حديث محبة الخير للمسلم",
    "title_ur": "سلسلۃ الذہب: مسلمان بھائی کے لیے خیر خواہی",
    "book": "Al-Muwatta & Sahih al-Bukhari #13",
    "matn_ar": "لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ مِنَ الْخَيْرِ.",
    "matn_en": "None of you truly believes until he loves for his brother what he loves for himself.",
    "matn_ur": "تم میں سے کوئی شخص اس وقت تک مومن نہیں ہو سکتا جب تک اپنے بھائی کے لیے وہی پسند نہ کرے جو اپنے لیے کرتا ہے۔",
    "narrator_ids": [
      "al_bukhari",
      "malik_ibn_anas",
      "nafi_mawla_ibn_umar",
      "abdullah_ibn_umar",
      "prophet_muhammad"
    ],
    "transmission_formulas": ["haddathana", "an", "an", "an"],
    "known_verdict": "SAHIH",
    "known_sub_verdict": "Sahih li-dhatihi (Golden Chain)",
    "badge_class": "sahih"
  },
  {
    "id": "hadith_talab_ilm",
    "title_en": "Seeking Knowledge is an Obligation (Talab al-Ilm)",
    "title_ar": "حديث طلب العلم فريضة على كل مسلم",
    "title_ur": "حدیث طلبِ علم (علم حاصل کرنا فرض ہے)",
    "book": "Sunan Ibn Majah #224",
    "matn_ar": "طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ.",
    "matn_en": "Seeking knowledge is an obligation upon every Muslim.",
    "matn_ur": "علم دین حاصل کرنا ہر مسلمان پر فرض ہے۔",
    "narrator_ids": [
      "al_tirmidhi",
      "al_zuhri",
      "anas_ibn_malik",
      "prophet_muhammad"
    ],
    "transmission_formulas": ["haddathana", "an", "an"],
    "known_verdict": "HASAN",
    "known_sub_verdict": "Hasan li-ghayrihi (Strengthened routes)",
    "badge_class": "hasan"
  },
  {
    "id": "hadith_seek_china",
    "title_en": "Seek Knowledge Even Unto China (Utlubul-Ilm)",
    "title_ar": "حديث: اطلبوا العلم ولو بالصين",
    "title_ur": "روایت: علم حاصل کرو خواہ چین جانا پڑے",
    "book": "Al-Du'afa of Al-Uqayli",
    "matn_ar": "اطْلُبُوا الْعِلْمَ وَلَوْ بِالصِّينِ، فَإِنَّ طَلَبَ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ.",
    "matn_en": "Seek knowledge even if it be in China...",
    "matn_ur": "علم حاصل کرو خواہ تمہیں چین جانا پڑے...",
    "narrator_ids": [
      "abu_atikah",
      "anas_ibn_malik",
      "prophet_muhammad"
    ],
    "transmission_formulas": ["an", "an"],
    "known_verdict": "DAIF",
    "known_sub_verdict": "Da'if Jiddan / Batil (Severely Weak)",
    "badge_class": "daif"
  },
  {
    "id": "hadith_hubb_al_watan",
    "title_en": "Love of the Homeland is from Faith",
    "title_ar": "حديث: حب الوطن من الإيمان",
    "title_ur": "روایت: وطن کی محبت ایمان کا حصہ ہے",
    "book": "Al-Maqasid al-Hasanah #386 (Fabrications)",
    "matn_ar": "حُبُّ الْوَطَنِ مِنَ الإِيمَانِ.",
    "matn_en": "Love of one's homeland is from faith.",
    "matn_ur": "وطن کی محبت ایمان میں سے ہے۔",
    "narrator_ids": [
      "habib_ibn_abi_habib",
      "malik_ibn_anas",
      "nafi_mawla_ibn_umar",
      "abdullah_ibn_umar",
      "prophet_muhammad"
    ],
    "transmission_formulas": ["an", "an", "an", "an"],
    "known_verdict": "MAWDU",
    "known_sub_verdict": "Mawdu' / La Asla Lahu (Fabricated)",
    "badge_class": "mawdu"
  }
];
